### ISSUE TITLE
Dell Display Issues: 4K & HDMI

### ISSUE THREAD

**Issue by gatorback** [Aaron9466/dell-optiplex-3090mff-opencore#3]
For the 3090-MFF i3-10105:  I have identified two video issues:

1) How to configure 3090-MFF for 4K Resolution?
2) Display Port to HDMI troubleshooting

Were these issues that you had to overcome somehow?  A response either here or in the link below would be appreciated.  Thank you

Details are posted in the original posting: https://www.tonymacx86.com/threads/is-there-any-reason-monterey-will-not-boot-on-a-optiplex-mff-3090-i3-10105.321903/

**Comment by Aaron9466** [comment]
https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html#turning-off-cfg-lock-manually

**Comment by Aaron9466** [comment]
Set Pre-Allocated DVMT to 64M
