### ISSUE TITLE
0.84关机没有断电

### ISSUE THREAD

**Issue by Civic315** [Aaron9466/dell-optiplex-3090mff-opencore#4]
大神，我尝试换了你0.84的EFI，发现关机不能断电，求解

**Comment by Aaron9466** [comment]
专门打了acpi补丁修复这个问题。我这里工作良好。

**Comment by Aaron9466** [comment]
已修复该问题。替换新的文件SSDT-SHUTDOWN.aml，参考新的config.plist修改你的config.plist中的apc->patch项目
