### ISSUE TITLE
USB NOT WORKING

### ISSUE THREAD

**Issue by durujavi** [Aaron9466/dell-optiplex-3090mff-opencore#5]
Hello, first of all, thank you very much for your work. I have installed Sonoma and when I put the UEFI, the USB ports of the Optiplex 3090 stop working. Could you help me, please? Thanks again.

**Comment by Aaron9466** [comment]
This `EFI` only applies to Optiplex 3090mff.you need to create your own usb port map.Refer to these links:[USB-ports-map-for-macOS-with-USBToolBox](https://github.com/perez987/USB-ports-map-for-macOS-with-USBToolBox) [ How To Map USB Ports on Hackintosh](https://www.youtube.com/watch?v=MFSaj5qf2eQ) [USB ports map for macOS with USBToolBox](https://www.tonymacx86.com/threads/how-to-usb-ports-map-for-macos-with-usbtoolbox.324437/)  [USB Port Mapping with Hackintool on macOS](https://chriswayg.gitbook.io/opencore-visual-beginners-guide/step-by-step/install-postinstall/usb-port-mapping)
